### PR TITLE
ForceAtlas2 bug fix + correction of a unit test

### PR DESCRIPTION
**Pull request by rangeonnicolas**
Hello!
One of the unit test didn't succeed, just because of a "use strict" statement.
Then, it seems that there was a mistake on ForceAtlas2, due to a mistake in a variable name (namely 'adjustSize' instead of 'adjustSizes')

### CODE REVIEW

**Comment by Yomguithereal** [comment]
Hello @rangeonnicolas. You are right indeed for ForceAtlas. Thanks for spotting this. However, I am not sure to get why adding `use strict` to those tests fixes something. Can you explain the issue a bit more please?

**Comment by rangeonnicolas** [comment]
Hello,
Concerning the unit test, I had this error when opening the file `/test/unit.html` with firefox and with Chrome :
img

However, I'm really not used to Qunit. Maybe this error is due to my version of JS, and this way of correcting is maybe not the best one. Do you want me to revert this commit?

**Comment by Yomguithereal** [comment]
Yes, drop the commit so I can merge your FA2 fix. I'll check the issue with `use strict`.

**Comment by rangeonnicolas** [comment]
commit dropped ;)

**Comment by Yomguithereal** [comment]
PR merged ;)

**Pull request merged**
