### PR TITLE
Fix bugs when Sigma was required with webpack

### PR DESCRIPTION
**Pull request by NicholasAntonov**
The var declerations inside if statements were being hoisted,
resulting in HTMLElement and Window always being set to undefined.

### CODE REVIEW

**Comment by lrenn** [comment]
Fixes #643 for me.

**Comment by Yomguithereal** [comment]
This seems fine but I must verify an edge case with Node before merging.

**Comment by neverfox** [comment]
Any word on this? Having to run off of a fork for webpack/React projects.

**Comment by PommeVerte** [comment]
I'm in the same situation

**Comment by Zigur** [comment]
+1 Any hope to see this fix merged?

**Comment by stuarthendren** [comment]
This fix works for me too!

**Comment by bripkens** [comment]
We are facing the same issue and the proposed change works for us as well.

**Comment by jimtom2713** [comment]
The proposed changed has worked for me as well. Any hope this gets merged soon? Or another fix?

**Comment by ktseytlin** [comment]
This proposed fix worked for me. I had to update both src/sigma.export.js and build/sigma.require.js (once it was downloaded via webpack by npm install sigma) with identical changes in both files.

Would be awesome to get this merged in!

**Comment by PommeVerte** [comment]
would be great to see this merged

**Comment by sim51** [comment]
There is an other way to get sigma with webpack.
I have describe it here : https://github.com/jacomyal/sigma.js/issues/730#issuecomment-238022674

**Comment by Yomguithereal** [comment]
Hello everyone, I just published a commit inspired by @NicholasAntonov but with one more safeguard to keep node.js' usage afloat. Can anyone try it and if it solves the issue, I will release a version asap so this stops buggering everyone?

**Comment by lavigneer** [comment]
> Can anyone try it and if it solves the issue

@Yomguithereal I was having this same problem and tested [31cc1ee](https://github.com/jacomyal/sigma.js/commit/31cc1ee3baf321d355f5597ba4d7e9fc8e2c6ff2) on top of version 1.1.0 published to npm and the issue is resolved. 

> I will release a version asap so this stops buggering everyone?

If a new version with this change can be released that would be awesome and greatly appreciated.

**Comment by Yomguithereal** [comment]
The version will soon be released. Still waiting on a pending PR on some zoom bug to publish release.

**Comment by PommeVerte** [comment]
Awesome! thanks.

**Comment by Yomguithereal** [comment]
The version is released

**Pull request closed without merging**
