### PR TITLE
fix #974: Node type is never set by GEXF parser

### LINKED ISSUE #974: Node type is never set by GEXF parser
When using GEFX parser, node type is never set, even when present in GEFX:
```
<node id="1" label="foo">
<viz:shape value="square"/> <!-- node type is never set -->
</node>
```

Edge type is set correctly though.

### PR DESCRIPTION
**Pull request by anwfr**
fix #974

### CODE REVIEW

**Comment by Yomguithereal** [comment]
Hello @anwfr. While I see the concern, I am not sure gexf's shape maps correctly 1:1 to sigma's type. In my recollections, gexf shape is a limited enum that does not map at all to sigma's rendering types. However, I see the use case very well. Could you check gexf's primer and tell me wether it's a free value variable or if it's constrained please?

**Comment by anwfr** [comment]
Hello @Yomguithereal,
Yes, gexf shape is a limited enum defined in https://gephi.org/gexf/1.2draft/gexf-12draft-primer.pdf as following:
`disc, square, triangle, diamond, image`

It seems that unmapped items are falling back to defaultNodeType, good.

**Comment by Yomguithereal** [comment]
Sigma doesn't by default support any of thos shapes except for the disc and the image (using a plugin). Did you by chance develop renderers for the other shapes that you need to support?

**Comment by anwfr** [comment]
I just used circle, square and diamond (with sigma.renderers.customShapes) which is meeting my needs :)

**Comment by Yomguithereal** [comment]
If an unknown type is mapped to default, I guess it should be fine thusly. Let's merge.

**Comment by Yomguithereal** [comment]
Hum... On second thought, could you add your changes to [those](https://github.com/anwfr/sigma.js/blob/0565438a89fbbf907968024b2d1cb832305fc607/plugins/sigma.parsers.gexf/sigma.parsers.gexf.js#L45-L52) lines, rather? It would be more consistent with how this plugin was designed.

**Comment by anwfr** [comment]
ok, done

**Pull request merged**
