### PR TITLE
add optional node/edge producers to sigma.neo4j.cypher. backcompatible.

### PR DESCRIPTION
**Pull request by dunnock**
Please merge... this small extension is back compatible, while provides possibility to customize created nodes and edges via custom transformers for neo4j data. I think anyone who uses this plugin would need possibility to customize colors, labels, sizes etc.
Thanks

### CODE REVIEW

**Comment by Yomguithereal** [comment]
@sim51, what do you think?

**Comment by dunnock** [comment]
Sorry Guys, I have mixed some webpack changes into this branch since PR. Therefore I withdrawing. @sim51 does not reply, so I don't think you 're going to merge it anyways, but ready to reinstantiate original change ed1a930.

**Comment by sim51** [comment]
Sorry for lag guys, I missed this PR ...

To be honest, I don't see the difference between your producer and the callback function.
I usually use this code snippet :

```
sigma.neo4j.cypher(
  { url: 'http://localhost:7474', user: 'neo4j', password: 'secret' },
  'MATCH (n) OPTIONAL MATCH (n)-[r]->(m) RETURN n,r,m LIMIT 500',
  { container: 'graph-container' } ,
  function(s) {
    s.graph.nodes().forEach( function(node) {
        if(node.neo4j_labels == "Movie") {
            node.color = '#25f17f';
            node.label = node.neo4j_data['title'];
        }
        else {
            node.color = '#f70017';
            node.label = node.neo4j_data['name'];
        }
    });
    s.refresh();
    s.startForceAtlas2();
 }
);
```

**Comment by dunnock** [comment]
Hi Sim, the difference is performance, e.g. in the callback it requires extra loop over nodes/edges, especially for large graphs. Thanks, Maxim

**Pull request closed without merging**
