### PR TITLE
Fix #1198 node size rendering using node.combined program

### LINKED ISSUE #1198: Q: Dynamic node size depending on zoom level
I'm visualizing a network of persons with Sigma - which works very nicely. These networks can be anything in size from very small (1-5) to very large (thousands of nodes).

Currently, the node size seems to stay fixed, independent on zoom level. When using a fixed nodesize on graph creation, the nodes either the nodes overlap (when zoomed out), or the nodes are too small (when zoomed in). See examples: 
image 
image

Also, when zoomed in, the image does not grow above its original size (although the label does). I would like the node to get bigger when zoomed in. Maybe it wouldn't grow linearly but slightly less when zoomed in.  

Is there a way to tweak this?

### PR DESCRIPTION
**Pull request by kaij**
Overcomes gl_PointSize limit and uses triangles w/inscribed circle

## Pull request type

Check the type of change your PR introduces:

- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: #1198 Rendered node size is restricted by WebGL platform when drawing using GL_POINTS (64px on macOS, see also: https://webglreport.com/?v=1). 

## What is the new behavior?

Merged the node and the node.image program and introduced the node.combined program which draws the node using gl.TRIANGLES. The center of the image texture is placed inside the inscribing circle. Added the node.combined program to e2e test, which now draws a larger sigma node into the center.

## Other information

Not all things are yet optimal:
- There is an "independent" bug in node.image for canvas size restrictions, I'll provide more details on this in a separate ticket
- I am not sure about the usage of `scaleRatio` vs `correctionRation` - is this the same? The merged programs node and node.image seem to use different naming. Also, is the `sqrtZoomRatio` the same as ratio?
- When zooming out heavily, the circles get smaller and become triangles (same behavious as in existing node program). I increased the marginRatio from 1.05 to 1.2, but can still see the behaviour with very small dots. Maybe this can be fixed somehow.
- The node.border program from the examples is not (yet) merged

programs.current.png:
image

### CODE REVIEW

**Comment by kaij** [comment]
I have an update to this, including border rendering and antialias fixes. But I'll need some time to integrate the changes from to my local fork. Biggest "problem" of integration currently is the node size calculation. I need this differently than with the sqrt ratio which makes it somewhat incompatible with other programs.

**Comment by kaij** [comment]
Implemented node borders. For some reason I do not yet understand, the border colors only work if having alpha=1 .

**Comment by kaij** [comment]
Example from real-world application (showing person images with borders, colored nodes with borders)
image

**Comment by kaij** [comment]
@jacomyal From my side, work on this is finished (split up in multiple pull request). Btw. the application is now online at https://nla.e-periodica.ch. Example: https://nla.e-periodica.ch/gnd-120335824. It's a research exploration tool for person networks (extracted from a corpus of 9 mio. pages from Swiss journals at www.e-periodica.ch). It also shows the limits when using it on very large graphs, as e.g. https://nla.e-periodica.ch/gnd-120335824?f=type:sent,element%253AArticle,page&f=max_confidence:0-5. 

Would be cool to see the node.combined integrated in the codebase. Please let me know if anything is missing or needs further evaluation.

image

**Comment by Yomguithereal** [comment]
Part of this was fixed by merging #1277. The `POINT` vs. `TRIANGLE` issue is duly noted and will be dealt with in subsequent changes (combining with a border seems to be fine with us in userland though).

**Pull request closed without merging**
