### PR TITLE
[Cypher plugin]: Correct documentation

### PR DESCRIPTION
**Pull request by sim51**
Change 'sigma.parsers.cypher' to 'sigma.neo4j.cypher'

### CODE REVIEW

**Comment by Yomguithereal** [comment]
Hello @sim51.You are right indeed concerning the erroneous documentation. But while we're there, shouldn't the plugin use the `sigma.parsers.cypher` namespace to remain coherent with its folder and the other namespaces?

**Comment by sim51** [comment]
Hi,
You have right for the cypher function, but there is also some helper functions for the communication between sigma & neo. 
Can I keep `sigma.neo` for them, and only put the cypher parser function into `sigma.parsers` package ? What do you think ?
Cheers.

**Comment by Yomguithereal** [comment]
I guess you could migrate all the plugin to the `neo4j` namespace since we are not "parsing" anything here strictly speaking. @jacomyal, what's your opinion?

**Comment by Yomguithereal** [comment]
Thanks you very much @sim51 :)?

**Pull request merged**
