### PR TITLE
Adding dots to the beginning and end of edges

### PR DESCRIPTION
**Pull request by jotunacorn**
This adds a plugin which enables the usage of dots near the beginning and end of edges. This can for instance be used when displaying a computer network to display interface status on each possible interface.

### CODE REVIEW

**Comment by Yomguithereal** [comment]
Hello @jotunacorn. All seems fine except that you should probably give a different name to you edge renderer so it doesn't override the classical `curvedArrow` one maybe.

**Comment by jotunacorn** [comment]
Okay. I looked at the `parallelEdges` plugin when creating this plugin and it seemed to override the classical `curvedArrow`. But you mean that I should create a new edge renderer for this e. g. `sigma.canvas.edges.dottedCurvedArrow`?

**Comment by Yomguithereal** [comment]
Yes, this would be it :).

**Comment by jotunacorn** [comment]
How do I go about using this new edge renderer instead of the standard one? And should I rename the `curve` one too?

**Comment by Yomguithereal** [comment]
You can switch the renderer to use either by specifying it through the settings (`defaultEdgeType` and `defaultNodeType`) or by setting the type of either your nodes or edges.

```js
s.graph.addEdge({
  id: '...',
  source: '1',
  target: '2',
  // set the type to render "à la carte"
  type: 'dotCurve'
});
```

**Comment by jotunacorn** [comment]
The more you know. Can the plugin be considered ready to be merged or do I need to change something more? :+1:

**Comment by Yomguithereal** [comment]
Well I guess it can be merged now :)

**Pull request merged**
