### PR TITLE
Added support for visualizing parallel edges using canvas curved/curvedArrow edges

### PR DESCRIPTION
**Pull request by 3ch01c**
[This guy's idea](http://stackoverflow.com/questions/13771956/can-d3-force-layout-visualize-multigraph) implemented it in sigma. It looks for a `count` attribute on edges and increases the amplitude of an edge's curve proportionately. Note that it's only currently implemented for canvas curve & curvedArrow edge types.

### CODE REVIEW

**Comment by Yomguithereal** [comment]
Hello @3ch01c. This is an interesting but rather edgy use case you present here. I am not sure this should enter the core library. It should probably become a plugin. Anyway, I am interested to know the kind of graph you want to visualize likewise. Do you carry edges predicates?

**Comment by 3ch01c** [comment]
I want to visualize multiple types of edges between the same nodes. In the past, I've done this by creating a separate graph for each edge type, or creating "filters" to toggle the display of edges, but sometimes it's useful to visualize all the edge types together while simultaneously retaining distinction between edge types. And when I say "type", I usually mean some custom categorical attribute on the edge, which I think is what you mean by "predicate"? I'll look into implementing it as a plugin.

**Comment by 21stcaveman** [comment]
Hey, I just tried this, pretty awesome, Thank you. It would be even more awesome if you could figure out a way to put different labels on each one of parallel edges though.

**Comment by 3ch01c** [comment]
@21stcaveman Labels should display correctly now, but edge labels plugin needs to be included before parallel edges plugin.

**Comment by 21stcaveman** [comment]
@3ch01c Awesome, I'll give it a try later today. Also, since we're improving things (!!), edgeHover doesn't work correctly, in the sense that it only hovers the very first edge, and all the events are fired for that edge only.

**Comment by 21stcaveman** [comment]
@3ch01c I fixed the issue with the edges not getting hovered, please see the parallel branch of my sigma.js repo

**Comment by Yomguithereal** [comment]
Hello @3ch01c. I am currently trying your example.

**Comment by Yomguithereal** [comment]
Quick question: would there be a solution not to have to add the count property on the edges on your own? Something like an index?

**Pull request merged**
