### PR TITLE
Adding A* plugin, see https://github.com/A----/sigma-pathfinding-astar

### PR DESCRIPTION
**Pull request by A----**
I wrote a (naive) implementation of A* for sigma.js and here it is.

### CODE REVIEW

**Comment by Yomguithereal** [comment]
Hello @A----,
Can you drop the minified file and the map file from your commit so I can merge your PR please?

**Comment by A----** [comment]
Done.

**Comment by Yomguithereal** [comment]
Thanks @A----, your plugin is now merged. Have a good day.

**Comment by cryptid11** [comment]
Where I - absolutely non js expert - can understand how to mount the plugin?

**Comment by A----** [comment]
You can see a live example here: http://a----.github.io/sigma-pathfinding-astar/
Simply include the plugin as a dependency. Then you can do:

```javascript
var s = new sigma({ […] }); // Your sigma instance
var path = s.graph.astar(srcId, destId, {
          undirected: true
        });
```

Please note that the plugin is not up-to-date on this repo, I have yet to do another pull-request.

**Comment by A----** [comment]
See PR #651.

**Comment by cryptid11** [comment]
Uh, thanks.

I need to color the path dynamically after somebody click the two nodes, is this possible? Is there an example of this?

**Comment by A----** [comment]
You pretty much have all you need in the example above.

Here, you'll find how to bind events: https://github.com/jacomyal/sigma.js/blob/master/examples/events.html

**Comment by cryptid11** [comment]
I just get the solution after a battle with js.

**Pull request merged**
